### ISSUE TITLE
Feature Request: Add @dit-throw to ignore error

### ISSUE THREAD

**Issue by khuezy** [michaelangeloio/does-it-throw#105]
Use case: Some workflows are expected to throw, eg a temporal workflow that aborts on a thrown error.

`//@dit-ignore` (or equivalent) should tell DIT to ignore the throw statement.

Why: I don't want DIT to give me the squigglies when I expect a function to throw.

**Comment by michaelangeloio** [comment]
@khuezy do we prefer `// @dit-ignore` or `// @does-it-throw-gnore`, or both?

**Comment by khuezy** [comment]
@michaelangeloio or maybe `@throw-ignore`? I'm fine with whatever is best.

**Comment by khuezy** [comment]
@michaelangeloio Can the `@` flag be configurable? I kinda like `// @it-throws` as an answer to `does-it-throw`.

**Comment by michaelangeloio** [comment]
#118 closes this
