### ISSUE TITLE
Availability on WebStorm 

### ISSUE THREAD

**Issue by lleifermann** [michaelangeloio/does-it-throw#69]
It would be great to also get this to run in WebStorm! Looks like LSP plugin support recently got released in WebStorm. Good starting point could be this blog post from jetbrains: https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

**Comment by michaelangeloio** [comment]
@lleifermann submitted to the JetBrains marketplace!

**Comment by lleifermann** [comment]
Dude is it Christmas again already?Thank you so much for pushing this through! Looking forward to trying it out 👀

**Comment by michaelangeloio** [comment]
Waiting for it to be reviewed and released by JetBrains! https://plugins.jetbrains.com/plugin/23434-does-it-throw-?noRedirect=true
